### PR TITLE
fix bool prop-types

### PR DESCRIPTION
**Pull request by madflow**
Currently we get: 

> Failed prop type: Form: prop type `options.readOnly` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

When using the `Form` component. This can be mitigated by changing the Boolean proptypes to the correct (?) `bool` constant.

https://github.com/facebook/prop-types

https://github.com/facebook/prop-types/issues/368

### CODE REVIEW

**Comment by simonv3** [comment]
We started seeing this when we migrated to React 17 I think.

**Comment by Beatusvir** [comment]
@madflow ohhh thats the issue? hahaha I've been trying to fix this for a couple of hours, I noticed the `boolean` but didnt realize the name was wrong.

**Comment by WesleyKapow** [comment]
Just hit this, in order to get it working without setting up a fork, I did the following:

```js
Form.propTypes.options = PropTypes.shape({
    readOnly: PropTypes.bool,
    noAlerts: PropTypes.bool,
    i18n: PropTypes.object,
    template: PropTypes.string,
    saveDraft: PropTypes.bool,
})
```

**Comment by gokhancetiner** [comment]
Hello,

Does anybody have an idea when this PR will merge? 

Thanks

**Comment by jafin** [comment]
@gokhancetiner  looks like a duplicate of this PR was merged 3 days ago #449

**Comment by TanyaGashtold** [comment]
Already fixed with https://github.com/formio/react/pull/449

**Pull request closed without merging**
