### PR TITLE
Refactored Form.jsx and fixed warnings.

### PR DESCRIPTION
**Pull request by azizk**
Hi!

I went ahead and rewrote/refactored the Form component whilst paying attention to compiler warnings and other details.
I also wanted to write tests but I didn't get that far yet. I did test it manually however.

Let's see if you like my changes and if you have suggestions to further improve the code. :+1:

### CODE REVIEW

**Comment by travist** [comment]
Wow! Thanks.  I will have one of our React developers take a look at this next week and see if we can get a new build with these improvements. Thanks for your contributions!

**Review by TanyaGashtold — APPROVED** [review]

**Comment by travist** [comment]
Unfortunately, this PR now needs to be rebased. We are planning another release of this library soon, so if you can get that in, we will be sure to include your changes.

**Review by alexandraRamanenka — APPROVED** [review]

**Review by AbdullahWins — APPROVED** [review]
good job!

**Comment by brendanbond** [comment]
Hey unfortunately some of these changes conflict with some upcoming changes to the react library - additionally, I don't really love the idea of using some kind of bespoke `propChanged` method rather than React builtins - I'm going to close this for now but if we end up using anything from it you will definitely get credit!

**Pull request closed without merging**
